In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error,root_mean_squared_error,r2_score,accuracy_score
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,LabelEncoder

In [2]:
df=pd.read_csv("C:\\Users\\rajh9\\Downloads\\placementdata.csv")
df=df.drop('StudentID',axis=1)
df.head(20)

CGPA  Internships  Projects  Workshops/Certifications  AptitudeTestScore  \
0    7.5            1         1                         1                 65   
1    8.9            0         3                         2                 90   
2    7.3            1         2                         2                 82   
3    7.5            1         1                         2                 85   
4    8.3            1         2                         2                 86   
5    7.0            0         2                         2                 71   
6    7.7            1         1                         1                 76   
7    7.7            2         1                         0                 85   
8    6.5            1         1                         0                 84   
9    7.8            1         3                         2                 79   
10   8.3            2         3                         2                 90   
11   7.9            1         3                         2                 90   
12   8.3            2         3                         2                 90   
13   7.7            1         1                         1                 74   
14   7.5            1         1                         1                 66   
15   7.4            0         2                         1                 78   
16   8.6            0         3                         0                 84   
17   8.2            2         3                         2                 90   
18   6.8            2         3                         0                 73   
19   7.4            1         2                         0                 70   

    SoftSkillsRating ExtracurricularActivities PlacementTraining  SSC_Marks  \
0                4.4                        No                No         61   
1                4.0                       Yes               Yes         78   
2                4.8                       Yes                No         79   
3                4.4                       Yes               Yes         81   
4                4.5                       Yes               Yes         74   
5                4.2                       Yes                No         55   
6                4.0                        No                No         62   
7                3.5                       Yes               Yes         59   
8                3.9                        No               Yes         75   
9                4.4                       Yes               Yes         85   
10               4.8                       Yes               Yes         82   
11               4.8                       Yes               Yes         71   
12               4.5                       Yes               Yes         84   
13               4.6                        No               Yes         63   
14               4.1                        No                No         61   
15               4.4                        No                No         63   
16               4.8                       Yes               Yes         62   
17               4.7                       Yes               Yes         84   
18               4.4                       Yes               Yes         72   
19               4.4                        No               Yes         58   

    HSC_Marks PlacementStatus  
0          79       NotPlaced  
1          82          Placed  
2          80       NotPlaced  
3          80          Placed  
4          88          Placed  
5          66       NotPlaced  
6          65       NotPlaced  
7          72       NotPlaced  
8          71       NotPlaced  
9          86          Placed  
10         88          Placed  
11         87          Placed  
12         83          Placed  
13         73       NotPlaced  
14         66       NotPlaced  
15         66       NotPlaced  
16         78          Placed  
17         86          Placed  
18         82          Placed  
19         63       Not

In [3]:
le=LabelEncoder()
y=le.fit_transform(df['PlacementStatus'])
y.reshape(1,-1)

array([[0, 1, 0, ..., 1, 1, 0]], shape=(1, 10000))

In [4]:
ct=ColumnTransformer(transformers=[('col1',OneHotEncoder(sparse_output=False,drop='first'),['ExtracurricularActivities','PlacementTraining'])],remainder='passthrough')

In [5]:
dF=ct.fit_transform(df)
new_columns = ct.get_feature_names_out()
new_df=pd.DataFrame(dF,columns=new_columns)
new_df

col1__ExtracurricularActivities_Yes col1__PlacementTraining_Yes  \
0                                    0.0                         0.0   
1                                    1.0                         1.0   
2                                    1.0                         0.0   
3                                    1.0                         1.0   
4                                    1.0                         1.0   
...                                  ...                         ...   
9995                                 1.0                         0.0   
9996                                 0.0                         0.0   
9997                                 1.0                         1.0   
9998                                 1.0                         1.0   
9999                                 0.0                         0.0   

     remainder__CGPA remainder__Internships remainder__Projects  \
0                7.5                      1                   1   
1                8.9                      0                   3   
2                7.3                      1                   2   
3                7.5                      1                   1   
4                8.3                      1                   2   
...              ...                    ...                 ...   
9995             7.5                      1                   1   
9996             7.4                      0                   1   
9997             8.4                      1                   3   
9998             8.9                      0                   3   
9999             8.4                      0                   1   

     remainder__Workshops/Certifications remainder__AptitudeTestScore  \
0                                      1                           65   
1                                      2                           90   
2                                      2                           82   
3                                      2                           85   
4                                      2                           86   
...                                  ...                          ...   
9995                                   2                           72   
9996                                   0                           90   
9997                                   0                           70   
9998                                   2                           87   
9999                                   1                           66   

     remainder__SoftSkillsRating remainder__SSC_Marks remainder__HSC_Marks  \
0                            4.4                   61                   79   
1                            4.0                   78                   82   
2                            4.8                   79                   80   
3                            4.4                   81                   80   
4                            4.5                   74                   88   
...                          ...                  ...                  ...   
9995                         3.9                   85                   66   
9996                         4.8                   84                   67   
9997                         4.8                   79                   81   
9998                         4.8                   71                   85   
9999                         3.8                   62                   66   

     remainder__PlacementStatus  
0                     NotPlaced  
1                        Placed  
2                     NotPlaced  
3                        Placed  
4                        Placed  
...                         ...  
9995                  NotPlaced  
9996                     Placed  
9997                     Placed  
9998                     Placed  
9999                  NotPlaced  

[10000 rows x 11 columns]

In [6]:
cols=['col1__ExtracurricularActivities_Yes','col1__PlacementTraining_Yes']
new_df[cols]=new_df[cols].astype(int)
new_df


col1__ExtracurricularActivities_Yes  col1__PlacementTraining_Yes  \
0                                       0                            0   
1                                       1                            1   
2                                       1                            0   
3                                       1                            1   
4                                       1                            1   
...                                   ...                          ...   
9995                                    1                            0   
9996                                    0                            0   
9997                                    1                            1   
9998                                    1                            1   
9999                                    0                            0   

     remainder__CGPA remainder__Internships remainder__Projects  \
0                7.5                      1                   1   
1                8.9                      0                   3   
2                7.3                      1                   2   
3                7.5                      1                   1   
4                8.3                      1                   2   
...              ...                    ...                 ...   
9995             7.5                      1                   1   
9996             7.4                      0                   1   
9997             8.4                      1                   3   
9998             8.9                      0                   3   
9999             8.4                      0                   1   

     remainder__Workshops/Certifications remainder__AptitudeTestScore  \
0                                      1                           65   
1                                      2                           90   
2                                      2                           82   
3                                      2                           85   
4                                      2                           86   
...                                  ...                          ...   
9995                                   2                           72   
9996                                   0                           90   
9997                                   0                           70   
9998                                   2                           87   
9999                                   1                           66   

     remainder__SoftSkillsRating remainder__SSC_Marks remainder__HSC_Marks  \
0                            4.4                   61                   79   
1                            4.0                   78                   82   
2                            4.8                   79                   80   
3                            4.4                   81                   80   
4                            4.5                   74                   88   
...                          ...                  ...                  ...   
9995                         3.9                   85                   66   
9996                         4.8                   84                   67   
9997                         4.8                   79                   81   
9998                         4.8                   71                   85   
9999                         3.8                   62                   66   

     remainder__PlacementStatus  
0                     NotPlaced  
1                        Placed  
2                     NotPlaced  
3                        Placed  
4                        Placed  
...                         ...  
9995                  NotPlaced  
9996                     Placed  
9997                     Placed  
9998                     Placed  
9999                  NotPlaced  

[10000 rows x 11 columns]

In [7]:
x=new_df.iloc[:,:-1].values
x

array([[0, 0, 7.5, ..., 4.4, 61, 79],
       [1, 1, 8.9, ..., 4.0, 78, 82],
       [1, 0, 7.3, ..., 4.8, 79, 80],
       ...,
       [1, 1, 8.4, ..., 4.8, 79, 81],
       [1, 1, 8.9, ..., 4.8, 71, 85],
       [0, 0, 8.4, ..., 3.8, 62, 66]], shape=(10000, 10), dtype=object)

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)
x_train

array([[0, 0, 7.6, ..., 4.1, 69, 75],
       [0, 1, 7.8, ..., 4.2, 79, 70],
       [0, 0, 7.4, ..., 4.1, 75, 66],
       ...,
       [1, 1, 8.1, ..., 4.8, 78, 84],
       [1, 1, 8.0, ..., 4.8, 81, 88],
       [1, 1, 7.4, ..., 4.3, 67, 73]], shape=(9000, 10), dtype=object)

In [9]:
model=LogisticRegression(max_iter=1000,)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [10]:
y_predict=model.predict(x_test)


In [11]:
acc_Poly=accuracy_score(y_test,y_predict)
acc_Poly

0.826

In [12]:
import pickle

In [13]:
pickle.dump(model, open('model.pkl','wb'))